# Generated by Django 3.2.5 on 2021-07-23 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kbcWinners', '0003_winner_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='picture',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 19, 36, 53, 67517, tzinfo=utc), verbose_name='date published'),
        ),
    ]
